#%RAML 0.8
---
title: Orders API
version: 1

/orders: 
  post: 
    description: Post new orders
    body: 
      application/json: 
        schema: !include post-orders-schema.json
        example: !include post-orders-example.json
    responses: 
      200: 
        body:
          application/json: 
            schema: !include simple-response-schema.json
            example: |
              { "message" : "Orders posted successfully" }
      400: 
       body:
          application/json: 
            schema: !include simple-response-schema.json
            example: |
              { "message" : "Bad request" }
  /{id}:
    get:
      description: Fetch orders by customerId
      responses: 
        200: 
          body:
            application/json: 
              schema: !include get-orders-response-schema.json
              example: !include get-orders-response-example.json
        400: 
         body:
            application/json: 
              schema: !include simple-response-schema.json
              example: |
                { "message" : "Bad request" }